title: Diamond Dust

url: "https://finalbuni.github.io"
baseurl: "/diamond-dust"

plugins:
  - jekyll-sitemap

collections:
  sections:
    output: true
    permalink: /sections/:name/
  chapters:
    output: true
    permalink: /chapters/:name/